### ISSUE TITLE
Question about the use of BertSum

### ISSUE THREAD

**Issue by DarlineFiedler** [Santosh-Gupta/ScientificSummarizationDataSets#3]
Hello,

I have a little problem I don't really understand how exactly you used BertSum. 
Or how to use BertSum in general. 
Do you have a tip or a more detailed description how to use BertSum?

**Comment by Santosh-Gupta** [comment]
Checkout the colab notebooks near the bottom, here's a direct link https://colab.research.google.com/drive/1IEHBsryjAjddS0jv7oJOi25_TxjVfA4F

**Comment by DarlineFiedler** [comment]
Thanks for your help. But now I get another error. I get empty brackets when running -format_to_bert. Maybe you know how to help. 

(base) D:\Studium\Bachelor Arbeit\Bachlorarbeit\Bachelorarbeit\BERT\BertSum\BertSum\src>python preprocess.py -mode format_to_bert -raw_path ../json_data -save_path ../bert_data -oracle_mode greedy -n_cpus 4 -log_file ../logs/preprocess.log
[('../json_data\cnndm_sample.train.0.json', Namespace(dataset='', log_file='../logs/preprocess.log', lower=True, map_path='../data/', max_nsents=100, max_src_ntokens=200, min_nsents=3, min_src_ntokens=5, mode='format_to_bert', n_cpus=4, oracle_mode='greedy', raw_path='../json_data', save_path='../bert_data', shard_size=2000), '../bert_data\bert.pt_data\cnndm_sample.train.0.bert.pt')]
[]
[]

**Comment by Santosh-Gupta** [comment]
I'm not sure, maybe paths may be off.

**Comment by DarlineFiedler** [comment]
Do you know the best way to test that?

**Comment by DarlineFiedler** [comment]
I actually just forgot to create the valid and test data. Now everything's going great.
