### ISSUE TITLE
How I get the generated summaries? 

### ISSUE THREAD

**Issue by DarlineFiedler** [Santosh-Gupta/ScientificSummarizationDataSets#5]
Hoi
 i have another question because i don't get an answer in the original git. Maybe you can help me. Do you know how I can get individual generated summaries? Best during training or validation where there is also an original. I would like to use another kind of evaluation but I need the sentences.

**Comment by Santosh-Gupta** [comment]
Is this using BertSum?

**Comment by DarlineFiedler** [comment]
Yes BertSum

**Comment by Santosh-Gupta** [comment]
https://github.com/Santosh-Gupta/BertSum

It's been a while, I remember I had this same issue, and discussed it a bit here

https://github.com/nlpyang/BertSum/issues/60

If possible, I recommend switching to hugginface's summarization training code, which is much better maintained 

https://github.com/huggingface/transformers/tree/master/examples/seq2seq#sequence-to-sequence
